[profile.default]
fs_permissions = [
  {access = "read", path = "./broadcast"},
  {access = "read", path = "./reports"},
]
libs = ["lib"]
out = "out"
remappings = ['@openzeppelin=lib/openzeppelin-contracts/']
src = "src"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
